data:
  path_to_data: C:\Users\heylu\Documents\github\ansiedade-e-pandemia\data\dataset
  train_filename: dataset_train.csv
  test_filename: dataset_test.csv
  validation_filename: dataset_valid.csv
  path_to_test_pred_scores: data/output/pred.txt

model:
  model_name: unicamp-dl/ptt5-base-portuguese-vocab
  summary_length: 128
  token_length: 512
  learning_rate: 1e-5
  num_epochs: 20  
  num_warmup_steps: 0 
  batch_size: 64 
  n_classes: 5